In [4]:
import numpy as np


In [17]:
#Testeo
dir(np)
xs=[1,2,3,4]
np.array(xs,dtype=np.float32)
np.linspace(0,1,7)
np.logspace(0,1,5)

#Matriz de mxn de num. aleatorios
np.random.rand(3,3)

#Propiedades de un array
an_array = np.ones((2,3))
print(an_array)
print(an_array.shape, an_array.ndim, an_array.size, an_array.dtype)
an_array.astype(np.int32)
print(an_array)

# Algunos métodos que modifican las dimensiones:
#
# reshape: Devuelve un nuevo array con las dimensiones indicadas cómo parámetro. Si alguno de los parámetros es igual a -1, se calculan las dimensiones para que sea factible el cambio.
#
# resize: el mismo efecto que “reshape” pero modifica el array en vez de devolver uno nuevo.
#
# T: sirve para transponer una matriz.
#
# ravel, flattened: “aplana” el array devolviendo todo en una sola dimensión

[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3) 2 6 float64
[[1 1 1]
 [1 1 1]]


In [54]:
#Operacioines propias de NP arrays
np.sum(np.arange(1000)) # suma un arreglo
arr = np.arange(16).reshape(4,4)
np.sum(arr, axis=0) #  de un arreglo 2d, suma solo un eje, el 0, el primero -> es decir , suma horizontal

#Indexacion en array
arr=arr.ravel()
arr[3:15]

#En matrices
a_matrix=np.arange(16).reshape((4,4))
a_matrix[1:3,2:4]

#Operaciones con mascaras en arreglos 
np.array([x for x in np.arange(50,100) if x%2==0])


array([50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82,
       84, 86, 88, 90, 92, 94, 96, 98])

In [370]:
import timeit
#Ejercicio 1 
pares_menor_A_100 = []

pares_menor_A_100=np.array([x for x in np.arange(100) if x%2==0])    

pares_menor_A_100_np=np.array(np.arange(100)%2==0)  #Usa SIMD

# %timeit me computa el tiempo de ejecucion estimado de la funcion parametro/operacion 
# -r x -> me dice que se toman x muestras/repeticiones tq en cada muestra se obtiene un tiempo promedio
# -n x -> indica que cada repeticion/muestra debe ejecutar la operacion/funcion x veces
# -o xs -> indica que el resultado debe guardarse en el objeto xs de salida tq luego puede utilizarse para obtener detalles sobre la medicion : tiempos minimo , media y desviacion estandar.

times=%timeit -o np.array([x for x in np.arange(100) if x%2==0])

print(times.timings)
 
%timeit np.array(np.arange(100) %2==0)


19.5 μs ± 124 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
[1.9311899994499982e-05, 1.9662669999524952e-05, 1.933831999776885e-05, 1.9509599998127668e-05, 1.9630170008167625e-05, 1.9513920007739216e-05, 1.9435559993144123e-05]
3.69 μs ± 10.2 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [86]:
#Ejercicio 2

secuencia = list(np.random.choice([False, True], size=100000))

res=0
for i in range(0,len(secuencia)-1):
    if(secuencia[i] or not secuencia[i+1]):
        res+=1

res_np=0
arr=np.array(secuencia)

np.array([False,True]*50000)

array([False,  True, False, ...,  True, False,  True])

In [205]:
#Ejercicio 4
#Desconozco la distribucion de X ...uso media y var muestral
def mean(x):
    res=0
    x=np.array(x,dtype=np.int32)
    res=x.sum()/x.size
    return res
    
def var(x):
    x=np.array(x)
    mean_arr=np.ones(x.size)*mean(x)
    x=x-mean_arr
    x=x**2
    return x.sum()/(x.size-1)

print(mean(np.random.randint(1,10,1000000)))   
print(var(np.random.randint(1,10,1000000))) 


4.998262
6.657556878612877


In [275]:
#Ejercicio 5
def esSimetrica(A):
    A=np.array(A)
    for i in range(0,len(A)):
        for j in range(0,len(A)):
            if(A[i][j]!=A[j][i]):
                return False
    return True        

A=np.array([[1,2,3],
            [0,7,6],
            [3,6,9]])

B=np.array([[1,2,3],
            [2,5,6],
            [3,6,9]])

esSimetrica(B)


[[1 2 3]
 [2 5 6]
 [3 6 9]]


True

In [359]:
#Ejercicio 6
A = np.random.rand(4,4)
B=A.T * A * 0.1 /0.1 #Producto elemento a elemento

print(A.T*A*0.1)

esSimetrica(A)
esSimetrica(B)
#El prod. de Hadamard genera una matriz simetrica entre A y At

[[0.0080787  0.02298322 0.02447196 0.00680297]
 [0.02298322 0.02827073 0.0032222  0.01807009]
 [0.02447196 0.0032222  0.09580648 0.01780693]
 [0.00680297 0.01807009 0.01780693 0.08973588]]
[[0.2842305  0.39644805 0.69010909 0.74635746]
 [0.5797285  0.53170224 0.05569804 0.32135286]
 [0.35461004 0.57851138 0.97880786 0.43493992]
 [0.09114891 0.56231317 0.40941124 0.94729022]]
[[0.08078698 0.22983223 0.24471961 0.06802967]
 [0.22983223 0.28270727 0.03222195 0.18070095]
 [0.24471961 0.03222195 0.95806483 0.17806929]
 [0.06802967 0.18070095 0.17806929 0.89735876]]


True

In [ ]:
#Ejercicio 7 
def block_multiplication(A,B):

    n = A.shape[0]
    assert(n % 2 == 0)

    # Completar
    A11 = A[0:2,0:2]
    A12 = A[0:2,2:4]
    A21 = A[2:4,0:2]
    A22 = A[2:4,2:4]

    B11 = B[0:2,0:2]
    B12 = B[0:2,2:4]
    B21 = B[2:4,0:2]
    B22 = B[2:4,2:4]

    C_11 = [[A11[0,0]*B11[0,0],np.dot(A11[0,:],B11[:,1])],
            [A11[1  ,0]*B11[0,0],np.dot(A11[1,:],B11[:,1])]]
    
    C_12 = [[np.dot(A11[0,:],B12[:,0])+B22[0,0]*A12[0,0] , np.dot(A11[0,:],B12[:,1])+np.dot(A12[0,:],B22[:,1])],
            [ np.dot(A11[1,:],B12[:,0]) + A12[1,0]*B22[0,0] , np.dot(A11[1,:],B12[:,1]) + np.dot(A12[1,:],B22[:,1])]]
    
    C_21 = [[ np.dot(A21[0,:],B11[:,0]) , np.dot(A21[0,:],B11[:,1]) ],
            [ np.dot(A21[1,:],B11[:,0]) , np.dot(A21[1,:],B11[:,1])]]
    
    C_22 = [[ np.dot(A21[0,:],B12[:,0]) + np.dot(A22[0,:],B22[:,0]) , np.dot(A21[0,:],B12[:,1]) + np.dot(A22[0,:],B22[:,1])],
            [ np.dot(A21[1,:],B12[:,0]) + np.dot(A22[1,:],B22[:,0]), np.dot(A21[1,:],B12[:,1]) + np.dot(A22[1,:],B22[:,1])]]
    

    return np.block([[C_11,C_12],[C_21,C_22]])

ex_matrix=np.array([[2,3,2,3],
                    [0,3,2,3],
                    [0,0,2,3],
                    [0,0,2,3]])

block_multiplication(np.eye(4),ex_matrix)

N = 4
A = np.array(np.random.rand(N,N))
B = np.array(np.random.rand(N,N)) # Falla ya que B no es TI
assert(np.allclose(A @ B,block_multiplication(A,B)))

print("Ok")